name: Run Selenium + Behave Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'  # cambia esto si usas otra versión

    - name: Install Python dependencies (sin requirements.txt)
      run: |
        pip install --upgrade pip
        pip install selenium behave

    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip xvfb libxi6
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo dpkg -i google-chrome-stable_current_amd64.deb || sudo apt-get -f install -y

    - name: Install Chromedriver
      run: |
        CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+' | head -1)
        CHROMEDRIVER_URL=$(curl -s "https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions-with-downloads.json" \
          | jq -r --arg ver "$CHROME_VERSION" '.channels.Stable.downloads.chromedriver[] | select(.platform == "linux64") | .url' | head -1)

        wget -O chromedriver_linux64.zip "$CHROMEDRIVER_URL"
        unzip -o chromedriver_linux64.zip
        chmod +x chromedriver-linux64/chromedriver
        sudo mv -f chromedriver-linux64/chromedriver /usr/local/bin/chromedriver



    - name: Run Behave tests
      run: |
        xvfb-run behave
        sudo apt-get install -y jq

